### PR TITLE
Incorrect display of speed.

### PR DESCRIPTION
**Pull request by niels1189**
Speed showing in TH/s when it is GH/s.

### CODE REVIEW

**Comment by s3inlc** [comment]
Which version of Hashcat are you running? If you are running the latest beta or builds from the repository the speed is wrong because Hashcat changed the speed displaying. We will soon update the client to be able to handle both speeds.
But we cannot just remove the `*1000` now as a lot of people are still running Hashcat 3.6 and their speed would be wrong then.

**Comment by blazer2x** [comment]
https://github.com/s3inlc/hashtopussy-agent/commit/8e5767612fbdcb5df9a28ec74c0f5edef9e89722

Using that client (0.45.0) should report the correct speed to the server

**Comment by niels1189** [comment]
Running latest Beta build from hashcat, so that explains it.

**Comment by niels1189** [comment]
Using the new binary does not fix the speed displayed on the agent.
Using the new binary does not decrease the speed displayed on the web server.

**Comment by s3inlc** [comment]
Which speed is shown to you on the client?
Are you running the agent in debug mode? If yes, can you please send some lines where we see the Hashcat machine readable output. If not, please run it again with debug enabled: 
`hashtopussy.exe debug`

**Comment by niels1189** [comment]
(one client: https://gyazo.com/fa6a46b937ddd0191dc393551e58ceeb.png)

Client version: 0.46.2
Hashtopus version: 3.6.0-328-ge6cb69e


Progress:  1.40% | Speed:371.84GH/s | Cracks:0    | Accepted:0    | Zapped:1448 | Queue:1
STATUS  3       SPEED   360459652       1000    EXEC_RUNTIME    14.201771       CURKU   6066689
        PROGRESS        751599544704    843538075968    RECHASH 0       2907452 RECSALT 0
1       REJECTED        29484952
{"action":"solve","token":"Z65f0iL0hJ","chunk":79,"keyspaceProgress":6066689,"progress":7515995
44704,"total":843538075968,"speed":360459652,"state":3,"cracks":[]}
{"action":"solve","response":"SUCCESS","cracked":0,"skipped":0,"zaps":[]}
Progress:  3.33% | Speed:360.46GH/s | Cracks:0    | Accepted:0    | Zapped:0    | Queue:1
STATUS  3       SPEED   358938874       1000    EXEC_RUNTIME    14.228601       CURKU   6066689
        PROGRESS        753387141504    843538075968    RECHASH 0       2907452 RECSALT 0
1       REJECTED        29484952
{"action":"solve","token":"Z65f0iL0hJ","chunk":79,"keyspaceProgress":6066689,"progress":7533871
41504,"total":843538075968,"speed":358938874,"state":3,"cracks":[]}

**Comment by s3inlc** [comment]
Ok thanks, it seems we found the issue client-side as the calculation for the prefix on H/s was wrong. A new binary will be provided soon.
On the server side the *1000 should then be removed (like proposed in this PR) and it should be also correct on the server.

**Comment by niels1189** [comment]
I am now, this pull request removes it on the website.
Probably best to merge it after the binary is ready.

**Comment by s3inlc** [comment]
The new agent capable of handling both Hashcat types is now pushed to the repository, with it also the speed adjustment.

**Pull request closed without merging**
